/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The public network parameters a client needs to reach TON. */
export declare class Config {
  /** Returns a config for TON mainnet from a bundled snapshot. */
  static mainnet(): Config
  /** Parses a config from the TON `global.config.json` format. */
  static fromJson(json: string): Config
  /**
   * Returns the same config with a different bound on how old a proven head may be.
   *
   * The default is generous, because a first sync takes a couple of minutes and the
   * head it lands on was read before the walk began. A caller who knows their server
   * is current, and who is reading a balance before acting on it, wants it tighter:
   * this is the only thing standing between a client and a server that proves a real
   * block from last week, since nothing inside a proof says when it was served.
   *
   * Zero refuses every head, which is a way to say the client should not proceed on a
   * proven read at all.
   */
  withMaxHeadAge(seconds: number): Config
  /** How old a proven head may be before a sync refuses it, in seconds. */
  get maxHeadAge(): number
}

/**
 * A connection to a single TON liteserver.
 *
 * Reads run one at a time over the single channel: the connection is behind an async
 * mutex, so overlapping calls from JavaScript serialize rather than corrupt the stream.
 */
export declare class TonClient {
  /** Connects to a liteserver from the config and completes the ADNL handshake. */
  static connect(config: Config): Promise<TonClient>
  /**
   * Connects and starts the walk from a key block proven on an earlier run.
   *
   * `anchor` is this client's root of trust: everything it goes on to believe is
   * derived from that block, so it is worth exactly what the storage it came from is
   * worth. Anything that can write to where a caller keeps one can choose what this
   * client believes. The binding stores nothing and picks no location; a `BlockId` is
   * an object with two buffers, and where it lives is the caller's decision.
   */
  static connectFrom(config: Config, anchor: BlockId): Promise<TonClient>
  /**
   * The key block this client's trust rests on, or null before it has synced.
   *
   * Save it and hand it to `connectFrom` on a later run to make that run's sync short.
   */
  anchor(): Promise<BlockId | null>
  /**
   * Walks the anchor forward to the network's current head.
   *
   * Without an anchor the walk starts at the config's init block, which is a first
   * sync and runs over every key block published since: minutes and tens of megabytes
   * against mainnet. With one it is a link or two.
   */
  sync(): Promise<SyncReport>
  /** Reads the liteserver's current masterchain head. */
  masterchainInfo(): Promise<ReportedMasterchainInfo>
  /**
   * Reads an account and proves it against a block this client established itself.
   *
   * `address` is a raw `workchain:hex` or user-friendly base64 address. Walks the
   * chain to a current head, reads the account there, and checks the proofs against
   * it, so nothing in the result rests on a block the caller supplied. The first call
   * pays for the walk; save `anchor()` and pass it to `connectFrom` next time.
   *
   * Every call walks. A caller reading several accounts should `sync()` once and pass
   * that head to `accountAt` rather than pay for a walk per account.
   */
  account(address: string): Promise<VerifiedAccount>
  /**
   * Reads an account at the current masterchain head without checking anything.
   *
   * The result is the server's word: the proof it sent comes back alongside,
   * unchecked. It is named for what it is, because the proven read is the one a caller
   * lands on without choosing and this is the exception.
   */
  accountReported(address: string): Promise<ReportedAccount>
  /**
   * Reads an account at a block the caller names, and proves it belongs to that block.
   *
   * The proofs are checked against `trusted`'s root hash, and for an account outside
   * the masterchain the shard block holding it is derived from the masterchain state
   * rather than taken from what the server named. A proof that does not check out
   * rejects; there is no unproved fallback. An account the block's state does not hold
   * comes back as `nonexistent`, which is a proved answer rather than a failure.
   *
   * `trusted` is taken on faith, so where it came from is the whole question. Taking it
   * from `masterchainInfo` on this same client proves nothing: that only shows the
   * server agrees with itself. The two sources that mean something are a block this
   * client proved, from `sync()` or `anchor()`, and a block the caller trusts
   * independently.
   */
  accountAt(address: string, trusted: BlockId): Promise<VerifiedAccount>
  /**
   * Reads an account's raw state and proofs at a given block.
   *
   * The bytes come back as the server sent them, unchecked and undecoded. This is the
   * way out for a caller who wants to keep the proofs, check them elsewhere, or check
   * them against an anchor obtained later, with `verifyAccount`.
   */
  accountState(address: string, block: BlockId): Promise<ReportedAccountState>
}

/** An account, decoded. */
export interface Account {
  /**
   * The balance in nanotons, as a decimal string.
   *
   * A string rather than a number: mainnet balances run past what a JavaScript number
   * holds exactly, so a number would round some of them silently.
   */
  balance: string
  /** The account status: `nonexistent`, `uninit`, `frozen`, or `active`. */
  status: string
  /**
   * The logical time just after the account's last transaction, as a decimal string.
   *
   * One past the logical time of that transaction itself, so it will not equal the
   * last transaction's own logical time as an explorer reports it.
   */
  lastTransLt: string
  /** The contract code as a bag of cells, present only for an active account. */
  code?: Buffer
  /** The contract data as a bag of cells, present only for an active account. */
  data?: Buffer
  /** The hash of the state the account had when it froze, present only when frozen. */
  stateHash?: Buffer
}

/** One account read as a server answered it, ready to be checked. */
export interface AccountRead {
  /** The account's address, raw `workchain:hex` or user-friendly base64. */
  address: string
  /** The root hash of the masterchain block the caller trusts, 32 bytes. */
  trustedRootHash: Buffer
  /**
   * The proof tying the account's shard block to the trusted block.
   *
   * Required outside the masterchain, where it is the step that ties the shard to a
   * block the caller trusts. Ignored for a masterchain account, which is in that
   * block's own state.
   */
  shardProof?: Buffer
  /** The account-state proof the server sent. */
  proof: Buffer
  /** The account state as a bag of cells. */
  state: Buffer
}

/** The raw bytes of an account read, as the server sent them. */
export interface AccountState {
  /** The masterchain block the state was read at. */
  block: BlockId
  /**
   * The shard block the server says holds the account.
   *
   * The server's word, and not what a check relies on: verification derives the shard
   * block from the masterchain state instead of believing this.
   */
  shardBlock: BlockId
  /** The proof tying the shard block to the masterchain block. Empty in the masterchain. */
  shardProof: Buffer
  /** The account state as a bag of cells. Empty for an account that does not exist. */
  state: Buffer
}

/**
 * The full identity of a block.
 *
 * This crosses in both directions: it comes back from a read, and it goes in as the
 * block a verified read is proved against.
 */
export interface BlockId {
  /** The workchain id, `-1` for the masterchain. */
  workchain: number
  /**
   * The shard prefix as a 16-digit lowercase hex string; a u64 does not fit a JS number.
   *
   * Read back in this form. Accepted on the way in with or without a `0x` prefix.
   */
  shard: string
  /** The block sequence number. */
  seqno: number
  /** The block root hash, 32 bytes. */
  rootHash: Buffer
  /** The block file hash, 32 bytes. */
  fileHash: Buffer
}

/** An account with the unchecked proof the server sent. */
export interface ReportedAccount {
  /** The reported value, not proof-verified. */
  value: Account
  /** The raw proof bytes the server sent, still unchecked. */
  proof: Buffer
}

/** An account's raw state with the unchecked proof the server sent. */
export interface ReportedAccountState {
  /** The reported bytes, not proof-verified. */
  value: AccountState
  /** The raw proof bytes the server sent, still unchecked. */
  proof: Buffer
}

/** A masterchain head with the unchecked proof the server sent. */
export interface ReportedMasterchainInfo {
  /** The head block's id, not proof-verified. */
  value: BlockId
  /** The raw proof bytes, still unchecked; empty for this response. */
  proof: Buffer
}

/** What one sync reached and what it cost. */
export interface SyncReport {
  /**
   * The head the walk proved. It is proved for the caller that asked and not kept:
   * what the client keeps is the last key block on the way, from `anchor()`.
   */
  head: BlockId
  /** How many links were checked, each one a validator signature set. */
  links: number
  /** How many replies the server took to finish the chain. */
  rounds: number
}

/**
 * An account proved to sit in the state of a block the caller trusts.
 *
 * Nothing this crate returns in this shape skipped the check. The shape itself is not a
 * guarantee, though, and the difference matters to anyone building on top: the Rust
 * `Verified<T>` has a private constructor and cannot be forged, while this crosses as a
 * plain object, so JavaScript being what it is, any `{ value, anchor }` a caller
 * assembles is indistinguishable from one that came from here. Treat it as a label on
 * this crate's output, not as a check on an object of unknown origin.
 */
export interface VerifiedAccount {
  /** The proved account. */
  value: Account
  /** The block the account was proved against. */
  anchor: BlockId
}

/**
 * Proves an account read against the block hash the read was checked to.
 *
 * `account` reads and proves in one call, and is what most callers want. This is
 * the same check on its own, for the case where the bytes and the anchor arrive
 * separately: bytes fetched now with `accountState` and an anchor that turns up later, or
 * bytes handed over by something that is not this client at all.
 *
 * The check reaches no network and depends on nothing but its argument, so the same
 * bytes always give the same answer. It throws if the proof does not root at the trusted
 * hash, or if the account does not bind to it.
 */
export declare function verifyAccount(read: AccountRead): Account
