// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Nirapod Labs

//! What this client accepts as an ed25519 signature, pinned rather than inherited.
//!
//! The rule is libsodium's `crypto_sign_verify_detached`, because that is what TON
//! validators sign and verify with, and the margins on the real chain are thin enough
//! that being stricter than the network is a way to stall rather than a free safety
//! margin. Two things establish it here.
//!
//! A differential pass compares this crate against `ed25519-dalek`'s `verify_strict`
//! over valid signatures and over corruptions of them, and requires them to agree.
//! Then the edge cases the two could disagree on are stated one by one, built out of
//! curve arithmetic rather than copied as hex, so a wrong constant cannot make a case
//! pass by not being the case it claims to be.
//!
//! `ed25519-dalek` is a development dependency and does not ship. It also produces the
//! valid signatures below, which is deliberate: signatures generated by the code under
//! test would prove only that it agrees with itself.

use curve25519_dalek::constants::ED25519_BASEPOINT_POINT;
use curve25519_dalek::edwards::CompressedEdwardsY;
use curve25519_dalek::scalar::Scalar;
use curve25519_dalek::traits::Identity;
use curve25519_dalek::EdwardsPoint;
use ed25519_dalek::{Signer, SigningKey, VerifyingKey};
use ton_net_block::signature::verify;

/// A fixed-seed generator, so every case below is the same on every run.
fn xorshift(state: &mut u64) -> u64 {
    *state ^= *state << 13;
    *state ^= *state >> 7;
    *state ^= *state << 17;
    *state
}

fn bytes(state: &mut u64, n: usize) -> Vec<u8> {
    (0..n).map(|_| (xorshift(state) & 0xff) as u8).collect()
}

fn seed(state: &mut u64) -> [u8; 32] {
    bytes(state, 32).try_into().expect("32 bytes")
}

/// What `ed25519-dalek` makes of the same three inputs.
fn dalek_accepts(public_key: &[u8; 32], message: &[u8], signature: &[u8]) -> bool {
    let Ok(signature) = <[u8; 64]>::try_from(signature) else {
        return false;
    };
    let Ok(key) = VerifyingKey::from_bytes(public_key) else {
        return false;
    };
    key.verify_strict(message, &ed25519_dalek::Signature::from_bytes(&signature))
        .is_ok()
}

/// Runs both verifiers and requires them to agree, returning what they said.
fn agreed(public_key: &[u8; 32], message: &[u8], signature: &[u8]) -> bool {
    let mine = verify(public_key, message, signature);
    let theirs = dalek_accepts(public_key, message, signature);
    assert_eq!(
        mine,
        theirs,
        "disagreement: key {}, signature {}, message {} bytes",
        hex(public_key),
        hex(signature),
        message.len()
    );
    mine
}

fn hex(b: &[u8]) -> String {
    use std::fmt::Write as _;
    b.iter()
        .fold(String::with_capacity(b.len() * 2), |mut out, x| {
            let _ = write!(out, "{x:02x}");
            out
        })
}

#[test]
fn a_valid_signature_is_accepted() {
    let mut state = 0x9E37_79B9_7F4A_7C15;
    for length in [0usize, 1, 32, 68, 200] {
        let key = SigningKey::from_bytes(&seed(&mut state));
        let message = bytes(&mut state, length);
        let signature = key.sign(&message).to_bytes();
        assert!(agreed(
            &key.verifying_key().to_bytes(),
            &message,
            &signature
        ));
    }
}

#[test]
fn the_two_implementations_agree_over_random_corruptions() {
    // Corrupting one byte of a signature, a key or a message is the ordinary way a
    // signature goes wrong, and it is where an equation transcribed slightly wrong
    // shows up. Both must refuse, and neither may refuse alone.
    let mut state = 0x1234_5678_9ABC_DEF0;
    let mut refused = 0;
    for _ in 0..300 {
        let key = SigningKey::from_bytes(&seed(&mut state));
        let mut public = key.verifying_key().to_bytes();
        let length = 1 + (xorshift(&mut state) % 96) as usize;
        let mut message = bytes(&mut state, length);
        let mut signature = key.sign(&message).to_bytes();

        match xorshift(&mut state) % 3 {
            0 => signature[(xorshift(&mut state) % 64) as usize] ^= 1 << (xorshift(&mut state) % 8),
            1 => public[(xorshift(&mut state) % 32) as usize] ^= 1 << (xorshift(&mut state) % 8),
            _ => {
                #[allow(
                    clippy::cast_possible_truncation,
                    reason = "this feeds % message.len() right after, so any truncation still yields a valid index"
                )]
                let at = (xorshift(&mut state) as usize) % message.len();
                message[at] ^= 1;
            }
        }
        if !agreed(&public, &message, &signature) {
            refused += 1;
        }
    }
    assert!(
        refused > 250,
        "only {refused} of 300 corruptions were refused"
    );
}

#[test]
fn a_signature_of_the_wrong_length_is_refused() {
    let key = SigningKey::from_bytes(&[7; 32]);
    let signature = key.sign(b"hello").to_bytes();
    let public = key.verifying_key().to_bytes();
    for cut in [0, 1, 63, 65] {
        let mut short = signature.to_vec();
        short.resize(cut, 0);
        assert!(!verify(&public, b"hello", &short));
    }
}

/// Two points of small order, derived rather than transcribed.
///
/// The identity has order one. The point with `y = 0` has order four: substituting into
/// the curve equation gives `x^2 = -1`, which has a root modulo the field prime, so the
/// encoding is a real point and not a rejected one.
fn small_order_points() -> Vec<[u8; 32]> {
    let identity = EdwardsPoint::identity().compress().to_bytes();
    let y_zero = [0u8; 32];
    assert!(
        CompressedEdwardsY(y_zero)
            .decompress()
            .expect("y = 0 is on the curve")
            .is_small_order(),
        "the y = 0 point should have small order"
    );
    vec![identity, y_zero]
}

#[test]
fn a_small_order_key_is_refused() {
    // A small-order key verifies against many messages, so accepting one would let a
    // signature say nothing while looking valid. libsodium refuses it and so does this.
    let mut state = 0xAAAA_BBBB_CCCC_DDDD;
    for key in small_order_points() {
        for _ in 0..8 {
            let signature = bytes(&mut state, 64);
            assert!(!verify(&key, b"anything", &signature));
            assert!(!dalek_accepts(&key, b"anything", &signature));
        }
    }
}

#[test]
fn a_small_order_r_is_refused() {
    // libsodium refuses a small-order R as well, so refusing it here keeps this client
    // from counting a signature the validators' own software would not.
    let key = SigningKey::from_bytes(&[11; 32]);
    let public = key.verifying_key().to_bytes();
    let honest = key.sign(b"message").to_bytes();
    for small in small_order_points() {
        let mut signature = honest;
        signature[..32].copy_from_slice(&small);
        assert!(!agreed(&public, b"message", &signature));
    }
}

#[test]
fn a_non_canonical_encoding_is_refused() {
    // A y-coordinate above the field prime is a second encoding of a point that already
    // has one. Accepting it would give a signature more than one valid form.
    const P: [u8; 32] = [
        0xed, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
        0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
        0xff, 0x7f,
    ];

    /// Adds the field prime to the y-coordinate, keeping the sign bit, when that still
    /// fits in 255 bits. Only the smallest few y-values have a second encoding.
    fn second_encoding(point: &[u8; 32]) -> Option<[u8; 32]> {
        let sign = point[31] & 0x80;
        let mut out = [0u8; 32];
        let mut carry = 0u16;
        for i in 0..32 {
            let sum =
                u16::from(point[i] & if i == 31 { 0x7f } else { 0xff }) + u16::from(P[i]) + carry;
            out[i] = (sum & 0xff) as u8;
            carry = sum >> 8;
        }
        if carry != 0 || out[31] & 0x80 != 0 {
            return None;
        }
        out[31] |= sign;
        Some(out)
    }

    // The identity encodes as y = 1, so y = 1 + p is its second encoding and is small.
    let identity = EdwardsPoint::identity().compress().to_bytes();
    let doubled = second_encoding(&identity).expect("y = 1 has a second encoding");
    assert_ne!(doubled, identity);
    assert_eq!(
        CompressedEdwardsY(doubled).decompress(),
        Some(EdwardsPoint::identity()),
        "the second encoding should decode to the same point"
    );
    assert!(!verify(&doubled, b"message", &[0u8; 64]));

    // And in R, over a key that is otherwise honest.
    let key = SigningKey::from_bytes(&[13; 32]);
    let public = key.verifying_key().to_bytes();
    let honest = key.sign(b"message").to_bytes();
    let mut signature = honest;
    signature[..32].copy_from_slice(&doubled);
    assert!(!agreed(&public, b"message", &signature));
}

#[test]
fn a_scalar_at_or_above_the_group_order_is_refused() {
    // S below the group order is what stops a signature from having a second valid form
    // with the same key and message. Adding the order back produces exactly that.
    let key = SigningKey::from_bytes(&[17; 32]);
    let public = key.verifying_key().to_bytes();
    let honest = key.sign(b"message").to_bytes();
    assert!(agreed(&public, b"message", &honest));

    let s: [u8; 32] = honest[32..].try_into().expect("32 bytes");
    let order = Scalar::ZERO - Scalar::ONE; // L - 1, the largest canonical scalar.
    let mut malleable = [0u8; 32];
    let mut carry = 0u16;
    let order_bytes = order.to_bytes();
    for i in 0..32 {
        // s + L, computed as s + (L - 1) + 1.
        let sum = u16::from(s[i]) + u16::from(order_bytes[i]) + carry + u16::from(i == 0);
        malleable[i] = (sum & 0xff) as u8;
        carry = sum >> 8;
    }

    let mut signature = honest;
    signature[32..].copy_from_slice(&malleable);
    assert!(
        !agreed(&public, b"message", &signature),
        "a scalar at or above the group order was accepted"
    );
}

#[test]
fn a_torsion_component_is_refused() {
    // Adding a point of small order to R leaves the cofactored equation satisfied and
    // breaks the uncofactored one. libsodium compares without cofactor slack, so this
    // client does too, and a verifier that multiplied through by the cofactor would
    // accept a signature TON refuses.
    let key = SigningKey::from_bytes(&[19; 32]);
    let public = key.verifying_key().to_bytes();
    let honest = key.sign(b"message").to_bytes();

    let r = CompressedEdwardsY(honest[..32].try_into().expect("32 bytes"))
        .decompress()
        .expect("R is on the curve");
    let torsion = CompressedEdwardsY([0u8; 32])
        .decompress()
        .expect("y = 0 is on the curve");
    let shifted = (r + torsion).compress().to_bytes();
    assert_ne!(shifted, honest[..32]);

    let mut signature = honest;
    signature[..32].copy_from_slice(&shifted);
    assert!(!agreed(&public, b"message", &signature));
}

#[test]
fn the_basepoint_is_not_small_order() {
    // A guard on the guards: if the small-order test were broken in the direction of
    // saying yes to everything, every case above would pass for the wrong reason.
    assert!(!ED25519_BASEPOINT_POINT.is_small_order());
    assert!(EdwardsPoint::identity().is_small_order());
}
